main:
    path: /
    defaults: { _controller: AppBundle:Default:index }
    methods: GET

company_json_page:
    path: /pages/company/
    defaults: { _controller: AppBundle:Pages:company }
    methods: GET